[package]
name = "ferrelex_macro"
version.workspace = true
edition.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
documentation.workspace = true
homepage.workspace = true
description = "Procedural macro internals for ferrelex — not intended for direct use"
keywords = ["lexer", "procedural-macro"]
categories = ["development-tools::procedural-macro-helpers"]

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1"
quote = "1"
syn = { version = "2", features = [ "full", "extra-traits", "visit", "visit-mut" ] }
ferrelex_core = { path = "../ferrelex_core", version = "0.2.1" }
rustc-hash = "2.1.1"

[dev-dependencies]
trybuild = "1"
macrotest = "1"
